site_name: Sistemes Marc Baiges
theme:
  name: material
  features:
   - navigation.sidebar
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra_css:
 - css/styles.css

nav: 

- Index:
    - index.md

- Sprint 2:
    - sprint2.md
- Sprint 3:
    - sprint-3_index.md
    - instalaciodomini.md
    - gestiodomini.md
    - ServidorNFS.md
    - ServidorSAMBA

- Sprint 4:
   - RAID.md
   - RAID1.md
   - RAID5.md

- Sprint 5:
  - Monitoratge.md
  - Servidoractualitzacions.md
  - auditoria.md