site_name: Sistemes Marc Baiges
theme:
  name: material
  features:
   - navigation.sidebar
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

extra_css:
 - css/styles.css

nav: 


- Sprint 3 Ubuntu:
   - Sprint3.md



- Sprint 5 Ubuntu:
  - Monitoratge.md
  - Servidoractualitzacions.md
  - auditoria.md




- Sprint 3 Windows:
  - windows3.md



- Sprint 5 Windows:
  - Auditories.md